Repository codesquad-members-2023-proj02-team04/second-hand, pull requests merged in 2023-06, with the labels that each got.

#12 chore #4: 컬러, 폰트, 전역 스타일 설정
  fe/.eslintrc.json
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/src/App.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/color.tsx
  fe/src/styles/font.tsx
  fe/tsconfig.paths.json
Labels: 🔥 FE

#15 feat #11: useFetch 커스텀 훅 구현
  fe/.eslintrc.json
  fe/craco.config.js
  fe/src/constants/index.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFetch/useFetch.test.ts
  fe/tsconfig.paths.json
Labels: 🔥 FE

#20 chore #4: themeProvider 적용
  fe/.eslintrc.json
  fe/src/App.tsx
  fe/src/components/common/Icon/index.tsx
  fe/src/components/common/NavigationBar/index.tsx
  fe/src/components/common/NavigationBar/style.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/src/styles/font.tsx
  fe/src/styles/theme.ts
  fe/tsconfig.json
Labels: 🔥 FE

#21 feat #17: Not Found 컴포넌트 초기 형태 구현
  fe/.eslintrc.json
  fe/public/index.html
  fe/src/components/common/notFound/index.tsx
  fe/src/components/common/notFound/style.tsx
Labels: 🔥 FE

#29 [BE] : 동네 목록 반환 기능 구현
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/LocationDTO.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/LocationListDTO.java
  be/src/main/java/team4/codesquad/secondhand/service/LocationService.java
Labels: 💻 BE, ☀️ feature

#30 [BE] #23 feat: 카테고리 목록 전체 조회 기능 구현
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/CategoryDTO.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/CategoryListDTO.java
  be/src/main/java/team4/codesquad/secondhand/service/CategoryService.java
Labels: 💻 BE

#18 [iOS] FEAT: TabBarController 추가 및 진입 로직 추가
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/Global/TabBarController.swift
  ios/Daangn/Daangn/Supporting Files/Base.lproj/Main.storyboard
  ios/Daangn/Daangn/Supporting Files/Info.plist
  ios/Daangn/Daangn/Supporting Files/SceneDelegate.swift
Labels: 🍎 iOS, ☀️ feature

#36 feat #35: navigation bar 구현 완료
  fe/src/components/common/NavBar/NavBarModalSearch/index.tsx
  fe/src/components/common/NavBar/NavBarModalSearch/style.ts
Labels: 🔥 FE, ☀️ feature

#38 feat #33: button common 컴포넌트 1차 구현
  fe/.eslintrc.json
  fe/src/assets/multiply.svg
  fe/src/assets/plus.svg
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/hooks/useFetch/index.tsx
  fe/tsconfig.paths.json
Labels: 🔥 FE, ☀️ feature

#31 feat #26: 상품 상세 정보 조회
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/controller/ProductController.java
  be/src/main/java/team4/codesquad/secondhand/domain/Product.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/ProductDetailDTO.java
  be/src/main/java/team4/codesquad/secondhand/exception/ExceptionHandlers.java
  be/src/main/java/team4/codesquad/secondhand/repository/ProductRepository.java
  be/src/main/java/team4/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/team4/codesquad/secondhand/service/ProductService.java
Labels: 💻 BE, ☀️ feature

#39 feat #27: Tab Bar common 컴포넌트 2차 구현
  fe/public/index.html
  fe/src/App.tsx
  fe/src/assets/arrowUp.svg
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/NavBar/NavBarModalSearch/index.tsx
  fe/src/components/common/TabBar/TabBarChat/index.tsx
  fe/src/components/common/TabBar/TabBarChat/style.ts
  fe/src/components/common/TabBar/TabBarProductDetail/index.tsx
  fe/src/components/common/TabBar/TabBarProductDetail/style.ts
  fe/src/components/common/TabBar/TabBarSellProduct/index.tsx
  fe/src/components/common/TabBar/index.tsx
  fe/src/components/common/TabBar/style.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/theme.ts
Labels: 🔥 FE, ☀️ feature

#45 Feature/fe/common 37
  fe/.eslintrc.json
  fe/src/App.tsx
  fe/src/assets/ellipsis.svg
  fe/src/assets/heart.svg
  fe/src/assets/index.tsx
  fe/src/assets/innerHeart.svg
  fe/src/components/common/Icon/index.tsx
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/NavBarBackBtn/style.ts
  fe/src/components/common/NavBar/NavBarHome/index.tsx
  fe/src/components/common/NavBar/NavBarHome/style.ts
  fe/src/components/common/NavBar/NavBarModal/index.tsx
  fe/src/components/common/NavBar/NavBarModal/style.ts
  fe/src/components/common/NavBar/NavBarPicker/index.tsx
  fe/src/components/common/NavBar/NavBarPicker/style.ts
  fe/src/components/common/NavBar/NavBarSegmentPicker/index.tsx
  fe/src/components/common/NavBar/NavBarSegmentPicker/style.ts
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/ProductList/ProductItem/index.tsx
  fe/src/components/common/ProductList/ProductItem/style.ts
  fe/src/components/common/ProductList/StatusLabel/index.tsx
  fe/src/components/common/ProductList/StatusLabel/style.ts
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/ProductList/style.ts
  fe/src/index.tsx
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/src/types/index.ts
  fe/src/utils/DecimalPoint.ts
  fe/src/utils/TimeCounter.ts
  fe/tsconfig.paths.json
Labels: 🔥 FE, ☀️ feature

#44 feat #40: Full To Refresh 커스텀 훅 구현
  fe/src/components/common/Spinner/index.tsx
  fe/src/components/common/Spinner/style.ts
  fe/src/components/common/TabBar/style.ts
  fe/src/hooks/useFullToRefresh/index.tsx
Labels: 🔥 FE, ☀️ feature

#47 feat #46: 홈화면 ui 구성 완료
  fe/src/App.tsx
  fe/src/components/common/Icon/index.tsx
  fe/src/components/common/NavBar/NavBarHome/style.ts
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/ProductList/style.ts
  fe/src/components/common/TabBar/style.ts
  fe/src/constants/index.ts
  fe/src/pages/Home/index.tsx
Labels: 🔥 FE, ☀️ feature

#50 [iOS] FEAT: 상품 목록 리스트 collection view 및 관련 view controller 작성
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionView.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionViewCell.swift
  ios/Daangn/Daangn/CategoryFilter/CateogryFilterDataSource.swift
  ios/Daangn/Daangn/Common/Radius.swift
  ios/Daangn/Daangn/Component/BorderView.swift
  ios/Daangn/Daangn/Component/PaddedLabel.swift
  ios/Daangn/Daangn/Component/ProductListImageView.swift
  ios/Daangn/Daangn/Component/ProductStateBadge.swift
  ios/Daangn/Daangn/Extension/CollectionViewLayout+layouts.swift
  ios/Daangn/Daangn/Extension/UILabel+style.swift
  ios/Daangn/Daangn/Extension/UIView+Radius.swift
  ios/Daangn/Daangn/Model/Category.swift
  ios/Daangn/Daangn/Model/ProductState.swift
  ios/Daangn/Daangn/ProductList/LoadCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionView.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListDataSource.swift
  ios/Daangn/Daangn/TempVC/TempHomeViewController.swift
  ios/Daangn/Daangn/TempVC/TempSalesViewController.swift
  ios/Daangn/Daangn/TempVC/TempTabBarController.swift
  ios/Daangn/Daangn/TempVC/TempWishListViewController.swift
Labels: 🍎 iOS, ☀️ feature

#51 [iOS] CHORE: ViewController 병합 작업
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/Controller/HomeViewController.swift
  ios/Daangn/Daangn/Controller/SalesViewController.swift
  ios/Daangn/Daangn/Controller/WatchlistViewController.swift
  ios/Daangn/Daangn/Global/TabBarController.swift
  ios/Daangn/Daangn/TempVC/TempHomeViewController.swift
  ios/Daangn/Daangn/TempVC/TempTabBarController.swift
  ios/Daangn/Daangn/TempVC/TempWishListViewController.swift
Labels: 🍎 iOS

#60 [iOS] FEAT, REFACTOR: 카테고리 화면 작성 및 2주차 리뷰 내용 반영
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/CategoryCollection/CategoryCollectionViewCell.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionView.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionViewCell.swift
  ios/Daangn/Daangn/Component/BorderView.swift
  ios/Daangn/Daangn/Component/CollectionViewLayoutGenerator.swift
  ios/Daangn/Daangn/Component/IDField.swift
  ios/Daangn/Daangn/Component/LoginButton.swift
  ios/Daangn/Daangn/Component/ProductListImageView.swift
  ios/Daangn/Daangn/Component/ProductStateBadge.swift
  ios/Daangn/Daangn/Component/ProfileImageButton.swift
  ios/Daangn/Daangn/Component/TownButton.swift
  ios/Daangn/Daangn/Controller/CategoryViewController.swift
  ios/Daangn/Daangn/Controller/CreateAccountViewController.swift
  ios/Daangn/Daangn/Controller/HomeViewController.swift
  ios/Daangn/Daangn/Controller/MyAccountViewController.swift
  ios/Daangn/Daangn/Controller/SalesViewController.swift
  ios/Daangn/Daangn/Controller/SellHistoryViewController.swift
  ios/Daangn/Daangn/Controller/WatchlistViewController.swift
  ios/Daangn/Daangn/Model/Category.swift
  ios/Daangn/Daangn/ProductList/LoadCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionView.swift
Labels: 🍎 iOS

#61 feat #48: 무한 스크롤 구현 완료
  fe/src/components/common/ProductList/index.tsx
  fe/src/hooks/Scroll/index.ts
  fe/src/pages/Home/index.tsx
Labels: 🔥 FE, ☀️ feature

#63 [FE] FEAT: Router 설정
  fe/src/App.tsx
  fe/src/components/common/TabBar/TabBarChat/style.ts
  fe/src/components/common/TabBar/TabBarHome/index.tsx
  fe/src/components/common/TabBar/TabBarHome/style.ts
  fe/src/components/common/TabBar/TabBarProductDetail/index.tsx
  fe/src/components/common/TabBar/TabBarProductDetail/style.ts
  fe/src/components/common/TabBar/TabBarSellProduct/style.tsx
  fe/src/components/common/TabBar/index.tsx
  fe/src/index.tsx
  fe/src/pages/ChatList/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/SalesList/index.tsx
  fe/src/pages/WishList/index.tsx
  fe/src/router.tsx
Labels: 🔥 FE, ☀️ feature

#64 feat #35: 로그인 네비게이션 바 구현
  fe/src/components/common/NavBar/NabBarDefault/index.tsx
  fe/src/components/common/NavBar/NabBarDefault/style.ts
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/NavBarModal/index.tsx
  fe/src/components/common/NavBar/NavBarSegmentPicker/index.tsx
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/ProductList/index.tsx
  fe/src/hooks/useFetch/index.tsx
  fe/src/pages/Home/index.tsx
Labels: 🔥 FE, ☀️ feature

#66 Feature/be/41 be 작성화면 띄우기
  be/src/main/java/team4/codesquad/secondhand/controller/ProductController.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/ProductRequestDTO.java
Labels: 💻 BE, ☀️ feature

#74 feat #73: 물품 등록하기 페이지 구현
  fe/src/assets/chevronRight.svg
  fe/src/assets/index.tsx
  fe/src/components/CategoryList/index.tsx
  fe/src/components/CategoryList/style.ts
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/NewProduct/NewImg/style.ts
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/NavBarModal/index.tsx
  fe/src/components/common/NavBar/NavBarModal/style.ts
  fe/src/components/common/NavBar/NavBarModalSearch/index.tsx
  fe/src/components/common/NavBar/NavBarModalSearch/style.ts
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/TabBar/TabBarSellProduct/style.tsx
  fe/src/hooks/useFetch/index.tsx
  fe/src/index.tsx
  fe/src/pages/Category/index.tsx
  fe/src/pages/Category/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.ts
  fe/src/router.tsx
  fe/src/types/index.ts
  fe/src/utils/GetRandomInt.ts
  fe/src/utils/debounce.ts
Labels: 🔥 FE, ☀️ feature

#75 feat #65: Login 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/assets/githubLogo.svg
  fe/src/assets/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/LocationList/index.tsx
  fe/src/components/common/LocationList/style.ts
  fe/src/components/common/NavBar/NavBarModal/style.ts
  fe/src/components/common/NavBar/NavBarModalSearch/index.tsx
  fe/src/components/common/NavBar/NavBarModalSearch/style.ts
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/TabBar/TabBarHome/index.tsx
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFullToRefresh/index.tsx
  fe/src/index.tsx
  fe/src/pages/Auth/constant.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Auth/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/LocationSetting/index.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/Login/style.ts
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/Registration/index.tsx
  fe/src/pages/Registration/style.ts
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#83 Feature/fe/newproduct 80
  fe/src/assets/camera.svg
  fe/src/assets/chevronDown.svg
  fe/src/components/CategoryList/index.tsx
  fe/src/components/CategoryList/style.ts
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/NewProduct/NewImg/style.ts
  fe/src/components/NewProduct/NewTitle/index.tsx
  fe/src/components/NewProduct/NewTitle/style.ts
  fe/src/components/common/TabBar/TabBarHome/index.tsx
  fe/src/hooks/useFetch/index.tsx
  fe/src/pages/Category/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#78 Feature/be/42 be 상품 작성 기능 구현
  be/build.gradle
  be/src/main/java/team4/codesquad/secondhand/configuration/S3Config.java
  be/src/main/java/team4/codesquad/secondhand/configuration/S3Properties.java
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/controller/ProductController.java
  be/src/main/java/team4/codesquad/secondhand/domain/Product.java
  be/src/main/java/team4/codesquad/secondhand/domain/ProductImage.java
  be/src/main/java/team4/codesquad/secondhand/exception/ExceptionHandlers.java
  be/src/main/java/team4/codesquad/secondhand/service/ProductService.java
  be/src/main/java/team4/codesquad/secondhand/service/S3UploaderService.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/ProductCreateResponseDTO.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/ProductDetailDTO.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/ProductRequestDTO.java
  be/src/main/resources/dummy_data.sql
Labels: 💻 BE

#87 [FE] 로그인 추가 구현 및 홈화면 동네설정 페이지 구현
  fe/.gitignore
  fe/src/App.tsx
  fe/src/components/CategoryList/index.tsx
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/NavBar/NavBarHome/index.tsx
  fe/src/components/common/NavBar/NavBarHome/style.ts
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/Spinner/index.tsx
  fe/src/components/common/Spinner/style.ts
  fe/src/constants/endpoint.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFullToRefresh/index.tsx
  fe/src/hooks/useInfiniteScroll/index.tsx
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Auth/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/LocationSearch/index.tsx
  fe/src/pages/LocationSetting/index.tsx
  fe/src/pages/LocationSetting/style.ts
  fe/src/pages/Login/index.tsx
  fe/src/pages/Login/style.ts
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/Registration/index.tsx
  fe/src/router.tsx
Labels: 🔥 FE, ☀️ feature

#97 Feature/be/96 be 회원 판매 내역 구현
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/controller/ProductController.java
  be/src/main/java/team4/codesquad/secondhand/repository/ProductRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/ProductRepositoryImpl.java
  be/src/main/java/team4/codesquad/secondhand/service/ProductService.java
  be/src/main/java/team4/codesquad/secondhand/service/S3UploaderService.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/ProductSearchCondition.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/UserSalesProductDTO.java
  be/src/main/java/team4/codesquad/secondhand/service/dto/UserSalesProductListDTO.java
  be/src/test/java/team4/codesquad/secondhand/service/ProductServiceTest.java
Labels: 💻 BE, ☀️ feature

#100 Fix #84: 로그인 기능 Flow 수정
  fe/src/constants/endpoint.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/Registration/index.tsx
Labels: 🔥 FE, ☀️ feature

#101 chore #98: 새 상품을 등록하기 위해서 api 연동
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/NewProduct/NewTitle/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/types/index.ts
Labels: 🔥 FE

#104 Feature/fe/location setting 82
  fe/src/App.tsx
  fe/src/components/common/ProductList/index.tsx
  fe/src/constants/endpoint.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFetchAll/index.tsx
  fe/src/hooks/usePullToRefresh/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#105 [iOS] FEAT: 로그인 정보 키체인 저장 및 로그아웃 구현
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/Common/Auth/AuthManager.swift
  ios/Daangn/Daangn/Common/Auth/KeychainManager.swift
  ios/Daangn/Daangn/Common/Auth/LoginResult.swift
  ios/Daangn/Daangn/Common/Auth/OAuthProvider.swift
  ios/Daangn/Daangn/Common/ErrorHandler.swift
  ios/Daangn/Daangn/Common/JWToken.swift
  ios/Daangn/Daangn/Common/Network/NetworkError.swift
  ios/Daangn/Daangn/Common/Network/NetworkManager.swift
  ios/Daangn/Daangn/Common/NetworkError.swift
  ios/Daangn/Daangn/Common/UserInfo.swift
  ios/Daangn/Daangn/Common/WindowHandler.swift
  ios/Daangn/Daangn/Controller/CreateAccountViewController.swift
  ios/Daangn/Daangn/Controller/LoginViewController.swift
  ios/Daangn/Daangn/Controller/MyAccountViewController.swift
  ios/Daangn/Daangn/Extension/UIAlertController+init.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionViewCell.swift
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/Image/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Image/daangn.imageset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Image/daangn.imageset/iTunesArtwork@1x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/Image/daangn.imageset/iTunesArtwork@2x.png
  ios/Daangn/Daangn/Resource/Assets.xcassets/Image/daangn.imageset/iTunesArtwork@3x.png
  ios/Daangn/Daangn/Supporting Files/SceneDelegate.swift
Labels: 🍎 iOS

#109 feat #108: 상품 상세 페이지 구현
  fe/src/assets/dot.svg
  fe/src/assets/index.tsx
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/ProductDetail/ProductDetailContent/index.tsx
  fe/src/components/ProductDetail/ProductDetailContent/style.ts
  fe/src/components/ProductDetail/ProductDetailImg/index.tsx
  fe/src/components/ProductDetail/ProductDetailImg/style.ts
  fe/src/components/common/Modal/index.tsx
  fe/src/components/common/Modal/style.ts
  fe/src/components/common/ProductList/ProductItem/index.tsx
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/TabBar/TabBarProductDetail/style.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/ProductDetail/style.ts
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#111 feat #110: 채팅 페이지 뷰 구현
  fe/src/App.tsx
  fe/src/assets/dots.svg
  fe/src/assets/index.tsx
  fe/src/assets/myBubbleTail.svg
  fe/src/components/Chat/ChatList/index.tsx
  fe/src/components/Chat/ChatList/style.ts
  fe/src/components/common/Button/style.ts
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/NavBarHome/index.tsx
  fe/src/components/common/NavBar/NavBarHome/style.ts
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/TabBar/TabBarChat/index.tsx
  fe/src/components/common/TabBar/TabBarChat/style.ts
  fe/src/hooks/useFetchAll/index.tsx
  fe/src/pages/Chat/index.tsx
  fe/src/pages/ChatList/index.tsx
  fe/src/pages/ChatRoom/index.tsx
  fe/src/pages/ChatRoom/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/LocationSetting/index.tsx
  fe/src/pages/LocationSetting/style.ts
  fe/src/pages/NewProduct/index.tsx
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#117 판매 페이지 구현 완료
  fe/src/assets/dots.svg
  fe/src/assets/index.tsx
  fe/src/components/CategoryList/index.tsx
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/NewProduct/NewTitle/index.tsx
  fe/src/components/NewProduct/NewTitle/style.ts
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Modal/index.tsx
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/NavBarPicker/index.tsx
  fe/src/components/common/NavBar/NavBarSegmentPicker/index.tsx
  fe/src/components/common/NavBar/NavBarSegmentPicker/style.ts
  fe/src/components/common/NavBar/index.tsx
  fe/src/components/common/NavBar/style.ts
  fe/src/constants/endpoint.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFetchAll/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.ts
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/SalesList/index.tsx
  fe/src/pages/SalesList/style.ts
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#114 feat #113: 새로운 물품 등록을 하면 데이터에 반영 완료
  fe/src/assets/dots.svg
  fe/src/assets/index.tsx
  fe/src/components/CategoryList/index.tsx
  fe/src/components/NewProduct/NewImg/index.tsx
  fe/src/components/NewProduct/NewTitle/index.tsx
  fe/src/components/NewProduct/NewTitle/style.ts
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Modal/index.tsx
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/hooks/useFetch/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/ProductDetail/index.tsx
  fe/src/router.tsx
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature

#118 feat #116: 관심 목록 페이지 구현
  fe/src/assets/index.tsx
  fe/src/assets/oppositeBubbleTail.svg
  fe/src/components/Chat/ChatList/index.tsx
  fe/src/components/ChatRoom/ChatBubble/index.tsx
  fe/src/components/ChatRoom/ChatBubble/style.ts
  fe/src/components/ProductDetail/ProductDetailContent/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/components/common/NavBar/NavBarBackBtn/index.tsx
  fe/src/components/common/NavBar/style.ts
  fe/src/components/common/NotFound/index.tsx
  fe/src/components/common/ProductList/ProductItem/index.tsx
  fe/src/components/common/ProductList/index.tsx
  fe/src/components/common/TabBar/TabBarChat/index.tsx
  fe/src/components/common/TabBar/TabBarChat/style.ts
  fe/src/components/common/TabBar/TabBarProductDetail/index.tsx
  fe/src/components/common/TabBar/TabBarProductDetail/style.ts
  fe/src/components/common/TextInput/index.tsx
  fe/src/components/common/TextInput/style.ts
  fe/src/constants/endpoint.ts
  fe/src/constants/index.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFetchAll/index.tsx
  fe/src/hooks/useInfiniteScroll/index.tsx
  fe/src/hooks/useLocationSet/index.tsx
  fe/src/pages/Chat/index.tsx
  fe/src/pages/ChatRoom/index.tsx
  fe/src/pages/ChatRoom/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/LocationSetting/index.tsx
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/WishList/index.tsx
  fe/src/pages/WishList/style.ts
  fe/src/types/index.ts
Labels: 🔥 FE, ☀️ feature
